# Generated by Django 3.2.7 on 2021-09-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletype',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
