# Generated by Django 3.2.7 on 2021-09-03 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210903_2336'),
        ('cards', '0002_alter_card_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='profiles',
            field=models.ManyToManyField(related_name='deck', to='accounts.Profile'),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('C', 'Close'), ('O', 'Open')], max_length=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Accept'), ('P', 'Pending'), ('D', 'Decline')], default='P', max_length=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.trade')),
            ],
        ),
    ]
